### ISSUE TITLE
Command will always parse response as JSON even when there is no JSON response

### ISSUE THREAD

**Issue by JamesMarino** [oracle-actions/run-oci-cli-command#18]
When a successful response is found from the OCI CLI, it will always try and JSON parse a response - as in the [code](https://github.com/oracle-actions/run-oci-cli-command/blob/709feba0de2694c0ff4311b64ca08faf75bf4937/src/main.ts#L52) 
```javascript
const stdout = cliResult.stdout ? JSON.parse(cliResult.stdout) : {};
```

Commands such as `oci ce cluster create-kubeconfig` do not respond with JSON. See below for a failed response when running this command:

```
Run oracle-actions/run-oci-cli-command@v1.1
Installing Oracle Cloud Infrastructure CLI
Executing Oracle Cloud Infrastructure CLI command
/home/runner/.local/bin/oci ce cluster create-kubeconfig --cluster-id *** --file $HOME/.kube/config --region *** --token-version 2.0.0 --kube-endpoint PUBLIC_ENDPOINT
New config written to the Kubeconfig file /home/runner/.kube/config
Error: Unexpected token N in JSON at position 0
```

Would there be a way to force a JSON response from the CLI or should we have some logic to see if the response is JSON and if not, don't parse the response. Happy to open a PR if this is the logical path to go down to solve this.

I'm also not too familiar with the API and if this would happen on any other commands - not sure how widespread this issue would be.

**Comment by Djelibeybi** [comment]
That's why we created [`@oracle-actions/configure-kubectl-oke`](https://github.com/oracle-actions/configure-kubectl-oke)
