### ISSUE TITLE
oci call fails : "os ns get"

### ISSUE THREAD

**Issue by mikarinneoracle** [oracle-actions/run-oci-cli-command#19]
https://github.com/mikarinneoracle/github-actions-oci/blob/main/.github/workflows/oci.yml

have the secrets, values are copied from my local .oci config that works fine

Error:
**The process '/home/runner/.local/bin/oci' failed with exit code 1**

**Comment by neleshgoel** [comment]
Facing similar issue

Error:
The process '/home/runner/.local/bin/oci' failed with exit code 1

**Comment by Djelibeybi** [comment]
I shall investigate ASAP. Thanks for letting me know.

**Comment by Djelibeybi** [comment]
Can you both please confirm you're using `@oracle-actions/run-oci-cli-command@v1.1.1`? Because my canary tests ran fine a few hours ago.

**Comment by mikarinneoracle** [comment]
Yes I am.

First 1.1 then 1.1.1 - the same error

https://github.com/mikarinneoracle/github-actions-oci/blob/main/.github/workflows/oci.yml#L28

**Comment by Djelibeybi** [comment]
If you add `silent: false` to the `with:` stanza, you should get more detail about why it's failing. Note that his may leak credentials, so I recommend either making your repo private first (if that's feasible) or creating a new private repo to test this in.

**Comment by mikarinneoracle** [comment]
Many thanks! This helped to debug: the fingerprint was incorrect (copy-paste error). Can close this one! Many thanks again!

**Comment by Djelibeybi** [comment]
Glad you solved it @mikarinneoracle. @neleshgoel, try using the `silent: false` option to see if that gives you sufficient information to resolve your issue. If not please open a new issue.
