### ISSUE TITLE
Github actions command output masking error 

### ISSUE THREAD

**Issue by RehanGhanchi** [oracle-actions/run-oci-cli-command#22]
Hi 
I am using OCI CLI in Github Actions to create a VCN. I am trying to pass the VCN ID to the next step which is to create Internet gateway. But the VCN ID outputted is masked. Hence, the Internet Gateway is unable to create because the VCN ID is masked. 
How to pass outputs from commands to subsequent commands?
Please find the code below.
Thanks in advance!
Code:

      - name: OCI VCN Creation
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-vcn-id
        with:
          silent: 'False'
          command: 'oci network vcn create --cidr-block ${{ github.event.inputs.VCN_cidr_block }} --compartment-id ${{ github.event.inputs.compartment-id }} --display-name "GitHub-Action-VCN" --region ${{ secrets.OCI_REGION }}'
          query: 'data.id' 
      - name: Get VCN Id 
        run: |
          echo ${{ steps.find-vcn-id.outputs.output }} | jq .

      - name: OCI VCN Igw creation
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        id: find-IGW-id
        with:        
          silent: 'False'
          command: 'oci network internet-gateway create --compartment-id ${{ github.event.inputs.compartment-id }} --is-enabled "true" --vcn-id ${{ steps.find-vcn-id.outputs.output }} --display-name "IGW1" --region ${{ secrets.OCI_REGION }} --output "json" --debug'
          query: 'data.id'
      - name: Get IGW Id 
        run: |
          echo ${{ steps.find-IGW-id.outputs.output }} | jq .

**Comment by Djelibeybi** [comment]
The output should not be masked to subsequent tasks in the job, only to the logs that are available via the GitHub web UI. You can see an example of that in the test action in this repo: https://github.com/oracle-actions/run-oci-cli-command/actions/runs/5663304696/job/15344815779

**Comment by RehanGhanchi** [comment]
> The output should not be masked to subsequent tasks in the job, only to the logs that are available via the GitHub web UI. You can see an example of that in the test action in this repo: https://github.com/oracle-actions/run-oci-cli-command/actions/runs/5663304696/job/15344815779

**Comment by RehanGhanchi** [comment]
Hi, 

Thanks a lot for the response. 
Even I assumed the same, that the masking only happens for the logs. 
But when I reference the VCN id from the 1st step and pass it to the 2nd step as shown in the example I get a "Resource not found - 404 error". Please find the full error below:

oci.exceptions.ServiceError: {'target_service': 'virtual_network', 'status': 404, 'code': 'NotAuthorizedOrNotFound', 'opc-request-id': 'D6963957**************', 'message': 'Authorization failed or requested resource not found.', 'operation_name': 'create_internet_gateway', 'timestamp': '2023-07-27T09:45:16.981355+00:00', 'client_version': 'Oracle-PythonSDK/2.108.0', 'request_endpoint': 'POST https://iaas.***.oraclecloud.com/201*****/internetGateways', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_notauthorizedornotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/iaas/20160918/InternetGateway/CreateInternetGateway for details on this operation's requirements. If you are unable to resolve this virtual_network issue, please contact Oracle support and provide them this full error message."}
Error: The process '/home/runner/.local/bin/oci' failed with exit code 1

**Comment by RehanGhanchi** [comment]
> Hi I am using OCI CLI in Github Actions to create a VCN. I am trying to pass the VCN ID to the next step which is to create Internet gateway. But the VCN ID outputted is masked. Hence, the Internet Gateway is unable to create because the VCN ID is masked. How to pass outputs from commands to subsequent commands? Please find the code below. Thanks in advance! Code:
> 
> ```
>   - name: OCI VCN Creation
>     uses: oracle-actions/run-oci-cli-command@v1.1.1
>     id: find-vcn-id
>     with:
>       silent: 'False'
>       command: 'oci network vcn create --cidr-block ${{ github.event.inputs.VCN_cidr_block }} --compartment-id ${{ github.event.inputs.compartment-id }} --display-name "GitHub-Action-VCN" --region ${{ secrets.OCI_REGION }}'
>       query: 'data.id' 
>   - name: Get VCN Id 
>     run: |
>       echo ${{ steps.find-vcn-id.outputs.output }} | jq .
> 
>   - name: OCI VCN Igw creation
>     uses: oracle-actions/run-oci-cli-command@v1.1.1
>     id: find-IGW-id
>     with:        
>       silent: 'False'
>       command: 'oci network internet-gateway create --compartment-id ${{ github.event.inputs.compartment-id }} --is-enabled "true" --vcn-id ${{ steps.find-vcn-id.outputs.output }} --display-name "IGW1" --region ${{ secrets.OCI_REGION }} --output "json" --debug'
>       query: 'data.id'
>   - name: Get IGW Id 
>     run: |
>       echo ${{ steps.find-IGW-id.outputs.output }} | jq . 
> ```

**Comment by RehanGhanchi** [comment]
My apologies I accidently closed the ticket  reopening it now.

**Comment by Djelibeybi** [comment]
Does it work with `silent: false`?

**Comment by RehanGhanchi** [comment]
we tried that too, it didn't work

**Comment by Djelibeybi** [comment]
Then your action configuration is incorrect, not the action itself. :) The tests are working, so the action code itself is working.

**Comment by Djelibeybi** [comment]
Do you see the correct VCN ID when you run with `silent: False`? If not, the `oci` command is either incorrect or getting the wrong value from the event source.

**Comment by RehanGhanchi** [comment]
Hi,
The problem seems to be quotation marks. When we retrieve the VCN ID using ${{ steps.find-vcn-id.outputs.output }} it has "". When we try to use raw_output to get the value without quotes, it returns an empty string. 

please find the error below.

Run echo  | jq .
  echo  | jq .
  shell: /usr/bin/bash -e {0}

**Comment by katraj-vertex** [comment]
any udpate on this issue.

**Comment by Djelibeybi** [comment]
Can you confirm that the command you're running only returns a single result? The `raw_output` value is only populated if the response from the API is a single value. Anything else, and it'll be blank. You may need to use `jq` to filter the response down instead.

**Comment by RehanGhanchi** [comment]
We are using a query  data.id along with the VCN create and when we try to print it, it is blank, below I have provided the command 

command: 'oci network vcn create --cidr-block ${{ github.event.inputs.VCN_cidr_block }} --compartment-id ${{ github.event.inputs.compartment-id }} --display-name "GitHub-Action-VCN" --region ${{ secrets.OCI_REGION }} --wait-for-state "AVAILABLE"'
          query: "data.id" 
      - name: Get VCN Id 
        run: |
          echo ${{ steps.find-vcn-id.outputs.raw_output }} | jq .

**Comment by Djelibeybi** [comment]
It must not be returning a single result. Try using `output` instead of `raw_output` to see what the actual response is.

**Comment by RehanGhanchi** [comment]
When we are using "output" we are getting the vcn id but still not able to create IGW, below provided vcn id output

VCN id: 
Run echo "\"ocid1.***.***.***.************************************************************\"" | jq .
"ocid1.***.***.***.************************************************************"

**Comment by Djelibeybi** [comment]
If you're getting the VCN ID, then you'll need to use `jq -r` to get the raw value from it. If that still doesn't work, then there's something wrong with the subsequent command or you're not getting the right ID as a response.

**Comment by RehanGhanchi** [comment]
jq -r does not work with oci actions. it only works as a direct Linux command, i.e. with echo 
below is the error after using it:

/home/runner/.local/bin/oci --query data.id network vcn create --cidr-block 10.0.0.0/16 --compartment-id *** --display-name GitHub-Action-VCN --region *** --wait-for-state AVAILABLE | jq -r

Usage: oci network vcn create [OPTIONS]

Error: No such option: -r

**Comment by Djelibeybi** [comment]
Correct. You would have to use the `output` of the `run-oci-cli-command` and pipe that to `jq`. 

Here's an example workflow that uses this pattern: https://github.com/Djelibeybi/oracle-actions-testing/blob/main/.github/workflows/run-oci-cli-command.yml

Here's the job output from that workflow: https://github.com/Djelibeybi/oracle-actions-testing/actions/runs/5814185568

The basic job has `silent: false` so you can see the output, but it works just fine with `silent: true` (or without the setting completely as the default is `true`).

**Comment by Djelibeybi** [comment]
I'm going to closae this issue. If you have any further concerns, either reopen this issue or create a new one. Thanks!
